#!/bin/bash
set -e

name="gh-token"
repo="carlsberg/$name"
tag=v0.1.0

extensionPath="$(dirname "$0")"
arch="$(uname -m)"

exe=""

if uname -a | grep Msys > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exe="${name}_${tag#v}_Windows_x86_64.exe"
  elif [ $arch = "arm64" ]; then
    exe="${name}_${tag#v}_Windows_arm64"
  fi
elif uname -a | grep Darwin > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exe="${name}_${tag#v}_Darwin_x86_64"
  elif [ $arch = "arm64" ]; then
    exe="${name}_${tag#v}_Darwin_arm64"
  fi
elif uname -a | grep Linux > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exe="${name}_${tag#v}_Linux_x86_64"
  elif [ $arch = "arm64" ]; then
    exe="${name}_${tag#v}_Linux_arm64"
  fi
fi

if [ "${exe}" == "" ]; then
  if [ "$(which go)" = "" ]; then
    echo "go must be installed to use this gh extension on this platform"
    exit 1
  fi

  exe="cmd.out"

  cd "${extensionPath}" > /dev/null
  go build -o "${exe}"
  cd - > /dev/null
else
  if [[ ! -x "${extensionPath}/bin/${exe}" ]]; then
    mkdir -p "${extensionPath}/bin"
    mkdir -p "${extensionPath}/tmp"
    rm -f "${extensionPath}/bin/*"
    gh release -R"${repo}" download "${tag}" -p "${exe}.tar.gz" --dir="${extensionPath}/tmp"
    tar -C "${extensionPath}/tmp" -zxf "${extensionPath}/tmp/${exe}.tar.gz"
    mv "${extensionPath}/tmp/${name}" "${extensionPath}/bin"
    chmod +x "${extensionPath}/bin/${name}"
    rm -rf "${extensionPath}/tmp"
  fi
fi

exec "${extensionPath}/bin/gh-token" "$@"
